from django.urls import path
from .views import (
    OrganizationDetailView,
    OrganizationListCreateView,
    OrganizationMemberListView,
    OrganizationMemberDetailView,
    OrganizationInvitationCreateView,
    OrganizationInvitationAcceptView,
    TeamListView,
    TeamCreateView,
)

urlpatterns = [
    path(
        "",
        OrganizationListCreateView.as_view(),
        name="organization-list-create",
    ),
    path(
        "<int:pk>/",
        OrganizationDetailView.as_view(),
        name="organization-detail",
    ),
    path(
        "<int:organization_id>/members/",
        OrganizationMemberListView.as_view(),
        name="organization-member-list",
    ),
    path(
        "<int:organization_id>/members/<int:pk>/",
        OrganizationMemberDetailView.as_view(),
        name="organization-member-detail",
    ),
    path(
        "<int:organization_id>/invitations/",
        OrganizationInvitationCreateView.as_view(),
        name="organization-invitation-create",
    ),
    path(
        "invitations/<str:token>/accept/",
        OrganizationInvitationAcceptView.as_view(),
        name="organization-invitation-accept",
    ),
    path(
        "<int:organization_id>/teams/",
        TeamListView.as_view(),
        name="team-list",
    ),
    path(
        "<int:organization_id>/teams/create/",
        TeamCreateView.as_view(),
        name="team-create",
    ),
]
